language: node_js
node_js: stable
cache:
  directories:
    - ~/.npm
    - node_modules
notifications:
  email: false
before_install:
  - npm install
install: 
  - npm install @semantic-release/exec
  - npm install @semantic-release/git
  - npm install travis-deploy-once
script:
  - travis-deploy-once "npm run semantic-release"
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  local-dir: dist
  on:
    branch: master
branches:
  except:
    - /^v\d+\.\d+\.\d+$/ 
